// 02-tienda-nextjs/src/components/LangSelector.tsx
'use client';

import { useState } from 'react';
import { useLang } from '@/context/LangContext';
import { languages, type Lang } from '@/lib/i18n/translations';

export default function LangSelector() {
  const { lang, setLang } = useLang();
  const [open, setOpen] = useState(false);

  function select(l: Lang) {
    setLang(l);
    setOpen(false);
  }

  return (
    <div className="relative" onBlur={(e) => { if (!e.currentTarget.contains(e.relatedTarget)) setOpen(false); }}>
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 px-2.5 py-1.5 border border-neutral-300 rounded text-xs font-semibold text-neutral-500 hover:border-neutral-900 hover:text-neutral-900 transition-colors"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label="Select language"
      >
        <span>{languages[lang].flag}</span>
        <span>{lang.toUpperCase()}</span>
        <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden>
          <path d="M1 3l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
        </svg>
      </button>

      {open && (
        <ul
          role="listbox"
          className="absolute right-0 top-[calc(100%+6px)] bg-white border border-neutral-200 rounded-lg shadow-lg py-1 min-w-[140px] z-50"
        >
          {(Object.entries(languages) as [Lang, { label: string; flag: string }][]).map(([code, info]) => (
            <li key={code} role="option" aria-selected={lang === code}>
              <button
                onClick={() => select(code)}
                className={`w-full flex items-center gap-2 px-3 py-2 text-sm hover:bg-neutral-50 transition-colors text-left
                  ${lang === code ? 'text-neutral-900 font-semibold' : 'text-neutral-500'}`}
              >
                <span>{info.flag}</span>
                <span>{info.label}</span>
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// 03-dashboard-vue/src/components/LangSelector.vue
<template>
  <div class="lang-selector" v-click-outside="closeMenu">
    <button
      class="lang-selector__toggle"
      @click="open = !open"
      :aria-expanded="open"
      aria-haspopup="listbox"
      aria-label="Select language"
    >
      <span>{{ languages[lang.value].flag }}</span>
      <span>{{ lang.value.toUpperCase() }}</span>
      <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
        <path d="M1 3l4 4 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
      </svg>
    </button>

    <ul v-if="open" class="lang-selector__menu" role="listbox">
      <li v-for="(info, code) in languages" :key="code" role="option" :aria-selected="lang.value === code">
        <button
          class="lang-option"
          :class="{ 'lang-option--active': lang.value === code }"
          @click="select(code)"
        >
          {{ info.flag }} {{ info.label }}
        </button>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useLang, languages } from '@/i18n/index.js';

const { lang, setLang } = useLang();
const open = ref(false);

function select(code) {
  setLang(code);
  open.value = false;
}

function closeMenu() {
  open.value = false;
}
</script>

<!-- Directiva click-outside registrada en main.js -->

<style scoped>
.lang-selector { position: relative; }

.lang-selector__toggle {
  display: flex;
  align-items: center;
  gap: 5px;
  background: transparent;
  border: 1px solid var(--border);
  color: var(--text-secondary);
  padding: 5px 10px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  font-family: inherit;
  transition: border-color 150ms, color 150ms;
}

.lang-selector__toggle:hover {
  border-color: var(--color-info);
  color: var(--text-primary);
}

.lang-selector__menu {
  position: absolute;
  top: calc(100% + 6px);
  right: 0;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 8px;
  list-style: none;
  padding: 4px;
  min-width: 140px;
  z-index: 200;
  box-shadow: var(--shadow-md);
}

.lang-option {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  background: none;
  border: none;
  color: var(--text-secondary);
  padding: 7px 10px;
  border-radius: 5px;
  font-size: 13px;
  font-family: inherit;
  cursor: pointer;
  text-align: left;
  transition: background 150ms, color 150ms;
}

.lang-option:hover,
.lang-option--active {
  background: rgba(59, 130, 246, 0.08);
  color: var(--color-info);
  font-weight: 600;
}
</style>
